// GitHub草生やし開始日
const GITHUB_START_DATE = new Date("2023-07-28");

// 経過日数を計算する関数
const getDaysFromStart = (startDate: Date): number => {
  const today = new Date();
  const diffTime = today.getTime() - startDate.getTime();
  const diffDays = Math.floor(diffTime / (1000 * 60 * 60 * 24));
  return diffDays;
};

export const PROFILE_JA = [
  "こんにちは、てづっぴです🦄！",
  "この子の名前は美少女ちゃん🎀！",
  "エンジニアをしています🕹️！",
  "栃木県出身🍓🥟！埼玉県在住🍘！",
  "JD：常時大学生（笑）🎓！",
  "SHOWROOM㍿で働いています🌃！",
  "DesingTomatoとしても活動中🍅！",
  "好きな言語はTypeScriptです❤️‍🔥！",
  "フレームワークはNext.js🚀！",
  "メイン領域はフロントエンド🏗️！",
  `GitHub草生やし"${getDaysFromStart(GITHUB_START_DATE)}日"継続中🌱！`,
  "サービスリリース準備中🐣！",
  "音楽を作るのが好き🎵！",
  "イラストを描くのが好き🎨！",
  "クリエイティブ全般が大好き💖！",
  "やりたいことが多すぎて困ります🤢",
  "ギターもベースもドラムもやる🎸🥁",
  "猫好き🐈！猫派🐈‍⬛！",
  "ロックマンエグゼシリーズ好き🌐！",
  "エヴァンゲリオン好き🪬！",
  "音楽は雑食🎧！激しいのが好き🤪！",
  "今は金髪👱！髪色探し中🪼！",
  "賃貸派だけど最後は家を買いたい🏡",
  "「音楽で飯を食いたい」人🍚！",
  "「1億円寄付したい」人🤝！",
  "「最後に死にたくない」人🪽！",
  "トマト好き🍅！カレー好き🍛！",
  "もうちょっとで終わりです🍽️！",
  "Safariに対応するのがダルい🥱",
  "「きこりの切株」を食べてます🪵",
  "終わりです👺！",
  "「きこりの切株」が終わりました🫩",
  "こんにちは、てづっぴです🦄！",
  "この子の名前は美少女ちゃん🎀！",
  "エンジニアをしています🕹️！",
  "栃木県出身🍓🥟！埼玉県在住🍘！",
  "ループしません🌀！",
  "幸せになってくださいね🌠",
];

export const PROFILE_EN = [
  "Hello, I'm Tedzuppi🦄!",
  "This girl's name is Bishoujo-chan🎀!",
  "I am an engineer🕹️!",
  "From Tochigi Prefecture🍓🥟! Living in Saitama Prefecture🍘!",
  "JD: Always a university student (lol)🎓!",
  "I work at SHOWROOM Inc.🌃!",
  "Also active as DesignTomato🍅!",
  "My favorite language is TypeScript❤️‍🔥!",
  "My framework is Next.js🚀!",
  "My main area is frontend🏗️!",
  `GitHub green squares "${getDaysFromStart(GITHUB_START_DATE)} days" streak🌱!`,
  "Preparing for service launch🐣!",
  "I love making music🎵!",
  "I love drawing illustrations🎨!",
  "I love all creative things💖!",
  "I have too many things I want to do🤢",
  "I play guitar, bass, and drums🎸🥁",
  "Cat lover🐈! Team cat🐈‍⬛!",
  "Love Rockman EXE series🌐!",
  "Love Evangelion🪬!",
  "I'm omnivorous with music🎧! Love intense stuff🤪!",
  "Currently blonde👱! Searching for hair colors🪼!",
  "Prefer renting but want to buy a house eventually🏡",
  "Person who wants to 'make a living with music'🍚!",
  "Person who wants to 'donate 100 million yen'🤝!",
  "Person who 'doesn't want to die last'🪽!",
  "Love tomatoes🍅! Love curry🍛!",
  "Almost finished🍽️!",
  "Supporting Safari is annoying🥱",
  "Eating 'Kikori no Kirikabu' (woodcutter's stump)🪵",
  "That's all👺!",
  "'Kikori no Kirikabu' is finished🫩",
  "Hello, I'm Tedzuppi🦄!",
  "This girl's name is Bishoujo-chan🎀!",
  "I am an engineer🕹️!",
  "From Tochigi Prefecture🍓🥟! Living in Saitama Prefecture🍘!",
  "Won't loop🌀!",
  "Please be happy🌠",
];
